apiVersion: v1
kind: ReplicationController
metadata:
  name: green
spec:
  replicas: 1
  selector:
    app: green
  template:
    metadata:
      name: green
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: uyuy2015/eks-blue-greendeployment:test8
        ports:
        - containerPort: 80
